const express = require('express');
const pages = require('../controllers/pageController');
const submissions = require('../controllers/submissionController');
const admin = require('../controllers/adminController');
const { loginRateLimiter, submissionRateLimiter } = require('../middleware/security');

const router = express.Router();
router.get('/', pages.home);
router.get('/internships', pages.home);
router.get('/courses', pages.courses);
router.get('/career-acceleration', pages.careerAcceleration);
router.get('/services', pages.page('services'));
router.get('/corporate-training', pages.page('corporate-training'));
router.get('/college-training', pages.page('college-training'));
router.get(['/about', '/about-us'], pages.page('about'));
router.get(['/contact', '/contact-us'], pages.page('contact'));
router.get('/jds-sat', pages.sat);
router.post('/contact', submissionRateLimiter, submissions.contact);
router.post('/enquiry', submissionRateLimiter, submissions.enquiry);
router.get('/admin', admin.requireLogin, admin.data, pages.adminDashboard);
router.post('/admin/login', loginRateLimiter, admin.login);
router.post('/admin/logout', admin.logout);
router.get('/admin/data', admin.requireLogin, admin.data, pages.adminDashboard);
router.post('/admin/settings/sat', admin.requireLogin, admin.updateSatVisibility);
router.post('/admin/settings/sat-timer', admin.requireLogin, admin.updateSatTimer);
router.post('/admin/career/jobs', admin.requireLogin, admin.createCareerJob);
router.post('/admin/career/jobs/:jobId/delete', admin.requireLogin, admin.deleteCareerJob);
router.post('/admin/delete/:collection/:id', admin.requireLogin, admin.delete);
router.use(pages.notFound);
module.exports = router;
